name: Automation test script

on:
  schedule:
    - cron: "00 18 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running test automation framework
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test logs
        path: logs/

    - name: Upload Screenshots as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/
        
    - name: Upload HTML report as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-reports
        path: report.html

    - name: Test Execution status
      run: echo "Test execution is completed"
      
    - name: Copy report to gh-pages folder
      if: always()
      run: |
        mkdir -p public/extent-reports
        cp report.html public/extent-reports/
    
        if [ -d "screenshots" ]; then
          mkdir -p public/extent-reports/screenshots
          cp -R screenshots/* public/extent-reports/screenshots/
          echo "Screenshots copied"
        else
          echo "No screenshots found (tests passed)"
        fi
        
        ls -R public/extent-reports

    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{secrets.PAT1}}
        clean: true
